name: SSH tunnel and forwarding using sshpass
version: 1.0.0
slug: auto_sshpass
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
host_network: true
options:
  username: ""
  hostname: ""
  password: ""
  local_host: "0.0.0.0"
  local_port: 8888
  remote_host: "0.0.0.0"
  remote_port: 8888
schema:
  username: string
  hostname: string
  password: string
  local_host: string
  local_port: integer
  remote_host: string
  remote_port: integer